# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c03478456697fe510c5291c7850d749113976bcee2fea1d61ca2398a8026947603054407124b253c7b87be4a9900fd80b51ad4cf33dab268a91feb84ea19c358

test:
  secret_key_base: e01f85343d3130c4eb70e3dbf43ada2eb2e329894f9de85a26a7a97786745b15b38a4c994b112c8913fc932f300420f7ce357b93c1f80054e9a410f7c00c21db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
